# git中的对称加密密钥
encrypt:
  key: 123456

# 访问http://localhost:8016的用户名及密码，config.client要与此一致
security:
  user:
    name: name
    password: password

# cloud-config-client就是用application.name与server.port来获取配置
# 要注意文件名要起好，因为client的spring.application.name要与配置文件前半段一致，注册服务要用
# 获取时使用ssh方式
spring:
  cloud:
    config:
      server:
        git:
          uri: git@git.github.com:name/configserver.git
          timeout: 30
          force-pull: true
          clone-on-start: true
      allow-override: true
  application:
    name: config-server-clustered

# cloud-config-client端只能指定一个端口，只要这个端口是CONFIG-SERVER-CLUSTERED下面其中一个就行
server:
  port: 8016

# 注册到集群中，这样访问http://localhost:8014
# 左边显示CONFIG-SERVER-CLUSTERED，就是spring.application.name
# 右边显示config-server-1，就是eureka.instance.instance-id
eureka:
  instance:
    instance-id: config-server-1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8014/eureka/,http://localhost:8015/eureka/

